### ISSUE TITLE
消息里，爱你城投稿请求，处理过的请求需要能继续显示

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#100]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/f1c5ca45-8232-4d84-b5d6-d1fb441feeca)
issue：需要一个全部已处理请求的分类，可以看到处理的时间和结果（通过和拒绝是可逆的），把未处理的请求放到全部未处理里。
background：现在的投稿处理了之后没有任何痕迹，直接就找不到了，很容易手误。
benifit：有利于查询投稿审批结果，防止手误，并且审批工作量清晰明了。

**Comment by ivanzhang2** [comment]
这个已处理过得投稿请求嘛，只要把当前用户能管理的专题都列出来的话，点进去，就能看到之前处理过得投稿的，包含已拒绝，忽略的。

这个地方在app里的逻辑是：用户如果有很多个能管理的专题，列表只会显示有过投稿请求的专题出来，我想是简书专题太多吧，我们可以把当前用户能管理的专题都列出来， 有新投稿的，靠前排。

这个需求肖新明来参与吧，数据关系和逻辑不熟悉的地方，可以让蔡志刚介绍一下，然后自己根据逻辑修复，测试。

**Comment by XiaoXinMing** [comment]
已经修复：

![2018-07-11 10-02-33屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/f6dcc7ad-a147-46b2-bb6e-638159908ea0)
