### ISSUE TITLE
之前同步代码之后创建专题的入口就没了，希望可以重新在编辑面板重新建一个创建专题入口，并且给普通用户开通创建专题的权限

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#101]
之前同步代码之后创建专题的入口就没了，希望可以重新在编辑面板重新建一个创建专题入口
![21](https://user-images.githubusercontent.com/36875687/41702213-de5d7c86-7561-11e8-87a4-f8572f1ecdbf.png)
希望让普通用户也可以创建专题，在发现页面点开更多热门专题，在专题页面靠右边即我标红的部位，  设置一个“创建属于我的专题”这样的按钮。以便普通用户也能自己创建专题
![23](https://user-images.githubusercontent.com/36875687/41702458-cb6dda3e-7562-11e8-81cd-9864d58d3508.jpg)

**Comment by XiaoXinMing** [comment]
普通用户已经正常可以创建专题。
已修复
需要前端开发人员加一个 “创建属于我的专题”的Button
@leikun222 

![2018-06-26 12-05-15](https://user-images.githubusercontent.com/39290488/41888667-448370b2-7939-11e8-91e5-b10e1c5b841b.png)

**Comment by tanyanqiong** [comment]
@wangyukun-hxb
