### ISSUE TITLE
APP上的常见帮助等官方文章需要提供

### ISSUE THREAD

**Issue by wangyukun-hxb** [haxibiao/ainicheng#102]
![image.png](https://images.zenhubusercontent.com/5ab452a24b5806bc2bcc0bde/277b1c6a-aaf8-489b-ae5f-b6f2fd23bb52)

**Comment by tanyanqiong** [comment]
爱你城签约作者申请指南  https://www.ainicheng.com/article/1375
提现没有到账怎么办？ https://www.ainicheng.com/article/12574
专题投稿须知  https://www.ainicheng.com/article/12580
如果你上传图片失败了  https://www.ainicheng.com/article/12579
爱你城账号绑定解绑相关问题汇总  https://www.ainicheng.com/article/12573
删除的文章如何找回，有回收站吗？ https://www.ainicheng.com/article/12572
对爱你城专题推荐作者的说明  https://www.ainicheng.com/article/12575
什么是爱你城内容领域优质作者及相关细则  https://www.ainicheng.com/article/12576
爱你城社区管理规则 https://www.ainicheng.com/article/12577

先用这九个吧，已经涉及到我们网站相关的了。https://www.ainicheng.com/ainichengguanfang 这个专题里还有剩下的相关文章。
