### ISSUE TITLE
爱你城网站搜索某专题后点关注，跳转页面数据不对

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/ainicheng#105]
![image.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/2e76ae74-95ad-4143-93ed-3ec15f1c80cb)

以下是跳转后的页面变成编辑面板页面
![image.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/b4104e34-fe22-418f-8383-7f986dd11d3e)

**Comment by XiaoXinMing** [comment]
修复完成，已经可以正常关注专题。

URL：https://www.ainicheng.com/search/categories

![2018-06-27 17-20-48屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/1fbad69b-5223-4d95-ba3a-e5dbc76d1c6b)
