### ISSUE TITLE
热门专题建议从文章数量和关注人数进行排序计算

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/ainicheng#106]
如图，做的文章最多的DOTA2专题都没有出现在热门第一页
![image.png](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/73047cae-0610-4259-b61e-322a82d6410b)

**Comment by XiaoXinMing** [comment]
已经修复:

按照文章数量和关注人数进行排序

![2018-07-11 10-25-06屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/d4c4cf55-fa77-4695-a228-004eff243d38)

**Comment by yangliu9494** [comment]
提议：热门应该按用户最近最多访问量和点击量排名，如果是按文章数量的话，排名第一的唯美图片是用爬虫爬的8千多篇文章，我们手动更新的内容短时间很难超越这个专题文章数量。

**Comment by XiaoXinMing** [comment]
按照热度排序（如图：）
![2018-07-14 18-39-17屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/1ddaf83e-af5a-4d50-8c99-34a7a835fe30)

确定 OK 就按照如下排序

**Comment by yangliu9494** [comment]
OK

**Comment by XiaoXinMing** [comment]
已经更改为:按照最近七天访问量从高到底排序

2018年07月23日16:14:43

麻烦运营测一下，测完Close
