### ISSUE TITLE
视频上传截屏未完成时，专题视频栏的排序会有几处空白的地方

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#108]
视频上传截屏未完成时，专题视频栏的排序会有几处空白的地方
![1.png](https://images.zenhubusercontent.com/5b23113902c4ee49414c3e43/8fc88050-2570-4ed3-8eed-295f90301640)

编辑编辑器在选主配图的时候也会出现排序空白
![11.png](https://images.zenhubusercontent.com/5b23113902c4ee49414c3e43/bb0aa062-7f17-49ef-942e-8447d39d9100)

**Comment by caizhigang1997** [comment]
该问题在下次视频模块上线会解决，请PM跟踪一下

**Comment by caizhigang1997** [comment]
已经解决
