### ISSUE TITLE
换掉用户头像里的这张图 

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#109]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/3becc290-4e2e-4ab3-9cfa-900c32f87e20)
背景：之前聪哥随便固定了一张图做用户头像，一大堆这个头像的用户连在一起，显的很像垃圾网站和网站的风格很不搭。
处理方式：能不能后台随机换成我们现在的那套默认头像里的图。
好处：现在的注册默认头像和网站的风格更搭，看起来更像真实用户。

**Comment by XiaoXinMing** [comment]
已修复
![2018-06-26 12-01-56](https://user-images.githubusercontent.com/39290488/41888572-bdea43be-7938-11e8-8415-afde567de421.png)

**Comment by tanyanqiong** [comment]
这个问题已经解决了
