### ISSUE TITLE
文章详情页没有文章字数统计信息

### ISSUE THREAD

**Issue by caizhigang1997** [haxibiao/ainicheng#111]
![image.png](https://images.zenhubusercontent.com/5ab1cb2e4b5806bc2bcbb686/a369b0ce-7ada-439c-8387-2c0d04ef0aed)

**Comment by XiaoXinMing** [comment]
已经修复完成

URL：https://www.ainicheng.com/article/422

![2018-06-27 18-07-09屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/c0e63c26-563e-497c-8327-af995d50e4bf)
