### ISSUE TITLE
网站评论 体验感优化

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#112]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/2eb10db0-809e-405e-b073-77b7cbad2480)
背景：在消息里的评论里点回复和查看对话，都不能直接跳到评论框，都是一个点开文章的操作。
需求：回复可以直接跳到评论回复，查看对话可以直接跳到该评论所在处。
好处：提升用户体验感，方便用户操作，不用重新再滑一遍长文找到评论再去回复了。

**Comment by wangyukun-hxb** [comment]
评论通知增加回复功能，并且重构了评论中心
