### ISSUE TITLE
爱你城文章编辑署名问题

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/ainicheng#114]
管理员修改文章后，文章作者发生改变。
![1530157957(1).png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/c43b2a5a-70ef-4690-a7cd-bd49fcef6bb1)
我觉得应该是保持原样比较好，因为作者和编辑并不是一个身份，编辑如果修改了文章，可以在其他位置提示。

**Comment by ayaotz233** [comment]
而且作者改变后，原作者也收不到评论之类的通知了

**Comment by ivanzhang2** [comment]
这个以前是by design:  比如 之前的编辑离职了，他的文章被后来的编辑修改过，就自动归到新的编辑身份下。 这个是之前的运营需要。

根据现在的情况，不自动更新原作者身份比较make sense .

就改过来吧
