### ISSUE TITLE
部分文章评论信息不同步

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#121]
部分文章评论信息不同步，这是其中一篇，还有琼琼的几篇我看到信息也不对
![2.png](https://images.zenhubusercontent.com/5b23113902c4ee49414c3e43/efdd843b-13cf-4471-ac54-4ebc9f995ffe)
![3.png](https://images.zenhubusercontent.com/5b23113902c4ee49414c3e43/dc41b2d1-a5ff-4423-b837-95514d1b1617)

**Comment by ivanzhang2** [comment]
高璇补充一点新的bug信息

**Comment by XiaoXinMing** [comment]
已经修复完成
文章： https://l.ainicheng.com/article/214
文章： https://l.ainicheng.com/article/1508
文章： https://l.ainicheng.com/article/749
文章： https://l.ainicheng.com/article/749
文章： https://l.ainicheng.com/article/749
文章： https://l.ainicheng.com/article/2984
文章： https://l.ainicheng.com/article/7709
文章： https://l.ainicheng.com/article/11320
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/12518
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/12523
文章： https://l.ainicheng.com/article/12524
文章： https://l.ainicheng.com/article/3671
文章： https://l.ainicheng.com/article/3671
文章： https://l.ainicheng.com/article/3671
文章： https://l.ainicheng.com/article/12523
文章： https://l.ainicheng.com/article/3671
文章： https://l.ainicheng.com/article/3671
文章： https://l.ainicheng.com/article/12501
文章： https://l.ainicheng.com/article/12501
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/11322
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
文章： https://l.ainicheng.com/article/12405
fix articles count_comments...
fix success
![2018-07-04 11-55-45屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/ada67d1d-1aec-410f-aac9-60f6aec0d441)

原：
![2018-07-04 11-50-26屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/d843306e-bb15-4cbd-87f8-058db6187259)

修复后：
![2018-07-04 12-01-25屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/ede7b7b9-f2cb-4545-8b18-beda152780fb)

**Comment by gaoxuan-haxibiao** [comment]
![2018-07-04 4 21 57](https://user-images.githubusercontent.com/36940267/42266013-c0c72b7c-7fa7-11e8-9b98-4cf97b612ba3.png)
我的另外一篇上周星期6发的帖子，时间变成了2个月前。。。，ID也变成了3670。

**Comment by XiaoXinMing** [comment]
我修这个问题的时候 好像时间和Article ID 就是这样的

**Comment by XiaoXinMing** [comment]
这个issue已经修复
