### ISSUE TITLE
网站个人主页 我创建的专题显示的是最近投稿的专题

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#123]
![2018-07-02 9 38 54](https://user-images.githubusercontent.com/36940267/42141534-630e953c-7ddc-11e8-8ffc-b2ce2b8ed202.png)

**Comment by XiaoXinMing** [comment]
已经修复完成

URL：https://l.ainicheng.com/user/4

![2018-07-02 18-10-32屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/8bce3a8d-6fd8-4d16-aab7-2fd753323fe4)
