### ISSUE TITLE
编辑面板写文章或者编辑文章，选择是上首页点击发布，刷新一次之后是否上首页会自动变成选择否上首页

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#130]
编辑面板写文章或者编辑文章，选择是上首页点击发布，刷新一次之后是否上首页会自动变成选择否上首页
![7](https://user-images.githubusercontent.com/36875687/42153897-f69995c4-7e16-11e8-8281-0b7cafe12134.png)
![8](https://user-images.githubusercontent.com/36875687/42153916-0768ebd4-7e17-11e8-800d-6f958e70663d.png)

**Comment by XiaoXinMing** [comment]
去掉这个地方的上首页控制先去掉了
