### ISSUE TITLE
视频上传成功后的视频截图压缩了尺寸，视频列表图片浏览体验很差。

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#134]
可以按照比例大小裁剪截图，保证图片内容比例正常。。。

![2018-07-03 5 32 00](https://user-images.githubusercontent.com/36940267/42212516-ea8716e4-7ee8-11e8-94cc-82caa443df9c.png)

![2018-07-03 5 32 18](https://user-images.githubusercontent.com/36940267/42213380-29428ccc-7eeb-11e8-9a62-2e645a359e77.png)

**Comment by caizhigang1997** [comment]
为了适应大多数的视屏截取尺寸，目前我们网站设置的视屏封面图截取比例是300X200。这个会考虑改善。有个建议~ 以后提问题如果能同时提出解决建议就最好了。

**Comment by gaoxuan-haxibiao** [comment]
我建议是裁剪截图，在保证不改变尺寸比例的前提下裁剪点多余的部分

**Comment by gaoxuan-haxibiao** [comment]
我建议是裁剪截图，在保证不改变尺寸比例的前提下裁剪点多余的部分

**Comment by caizhigang1997** [comment]
ok,明白你的意思。那这个ISSUE下面不关。到时候弄好了会通知你，到时候我们一起测测。

**Comment by gaoxuan-haxibiao** [comment]
好，前面是手机操作不小心点错了关了…

**Comment by caizhigang1997** [comment]
以后视屏上传截图工作会交给qcloud处理
