### ISSUE TITLE
专题列表的推荐跟热门排序一样

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#136]
![2018-07-04 9 21 05](https://user-images.githubusercontent.com/36940267/42251791-f9a9802a-7f6b-11e8-85ce-ea2489952b20.png)
![2018-07-04 9 21 14](https://user-images.githubusercontent.com/36940267/42251803-0f8bdae6-7f6c-11e8-89e5-d67a43aa3460.png)

根据顶部的热门专题标题，是不是可以合并成一个。。。

**Comment by caizhigang1997** [comment]
推荐与热门是两个不同的逻辑。<b>推荐可能更贴近个人的喜好，而热门可能就是从整个网站层面来考虑了</b>
<b>推荐TabPanel</b>：后面做推荐模块会根据用户画像来推荐专题，目前是按照专题的创建时间来排序的。
<b>热门TabPanel</b>：目前系统是根据专题的被关注数来排序的。

PS:ISSUE记得Assign~

**Comment by caizhigang1997** [comment]
有一个类似的ISSUE,这个先关闭了.
