### ISSUE TITLE
爱你城新视频首页

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/ainicheng#138]
１．　杨柳负责需求
２．　高璇负责页面样式，交互
３．　肖新明负责后端代码绑定

更新状态了，回复这个issue

**Comment by ivanzhang2** [comment]
@XiaoXinMing　绑定这个页面的时候，有vue相关的问题，不懂的可以请教高璇，蔡志刚．

**Comment by gaoxuan-haxibiao** [comment]
@XiaoXinMing  样式交互已经完成，可以绑定数据了。。。

**Comment by XiaoXinMing** [comment]
已经给Admin增加了置顶视频专题功能，数据已取到页面上.

**Comment by XiaoXinMing** [comment]
完成
