### ISSUE TITLE
专题修改时的专题搜索失效

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/ainicheng#144]
文章发布后，管理员进行专题修改时，无法搜索专题；
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/d51ea35c-62c3-4904-87ce-c6852ecbb7f9)
点搜索没反应

**Comment by XiaoXinMing** [comment]
已经修复

原因：这里原本是给搜索框做了键盘监听事件（通过回车键 可以检索出内容），目前已经为搜索按钮添加了点击事件。

![2018-07-07 16-57-42屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/8dcc5285-0595-45db-af47-aec0ea627471)
