### ISSUE TITLE
网站关键词优化

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#145]
1.把网站现在关键词改为：恋爱游戏 电子竞技  卡牌  角色扮演   游戏视频  热门资讯 社交攻略  交友聊天必备 
2.根据关键词已已经创建好了八个专题，未登录情况下在首页固定显示这八个专题。

**Comment by caizhigang1997** [comment]
这个网站已经更新,8个官方专题也会在未登录状态下优先显示.
