### ISSUE TITLE
专题优化

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#146]
1.给专题管理加一个搜索，有助于运营人员管理，节约时间。
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/ea9ee64c-b601-4d72-8ea4-f0c5292ebf21)

2.优化专题相关性
加上相关专题这一栏，让编辑人员可以手动组合相关一系列的专题，增强内容的连贯性，留住用户，减低跳出率。
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/1a27c50a-13ae-4f45-a582-09cd4696cb67)

**Comment by caizhigang1997** [comment]
1.第一个ISSUE,补充一点 视频管理页面,文章管理界面 也可考虑加入
2.目前能想到的关联规则是：这个专题下所有文章的其它分类（文章与分类是多对多关系）。大家可以补充~

**Comment by XiaoXinMing** [comment]
已经实现：
2018年07月23日17:37:20
![2018-07-23 17-33-28屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/a0fcc611-f178-46eb-a4a6-116dc931b79e)
