### ISSUE TITLE
app graphql  需求(2)

### ISSUE THREAD

**Issue by wangyukun-hxb** [haxibiao/ainicheng#148]
### 1.文章没有图片，但是cover字段返回了网站链接
![image.png](https://images.zenhubusercontent.com/5ab452a24b5806bc2bcc0bde/f08a8492-9760-49c6-bd59-80ef6c30e8ef)

#### 搜索中心：
热门专题(支持单个query)
热门搜索（支持翻页）
历史搜索query（以及清除单个、全部历史搜索的mutation）
![image](https://user-images.githubusercontent.com/36919271/42669181-af6ff580-8686-11e8-900d-8dff0db7ee92.png)
#### 搜索结果：
相关用户、专题、文集、文章(可以offset)
![image](https://user-images.githubusercontent.com/36919271/42669148-911aaa44-8686-11e8-9091-26a7f5d43856.png)

### 3. 喜欢、收藏、关注等内容按时间倒叙返回

**Comment by caizhigang1997** [comment]
问题基本上都定位到了。等下周重构完后端<b>文章与图片的关系</b>再开始修这些问题。1，2个ISSUE刚好依赖与这个重构逻辑。

**Comment by caizhigang1997** [comment]
已经修复
