### ISSUE TITLE
网站-新版专题主页-能切换只看视频模式

### ISSUE THREAD

**Issue by XiaoXinMing** [haxibiao/ainicheng#150]
1. 能来回切换只看视频，和只看文章、动态
2. 视频模式下，只需要热门和最新两个tab

**Comment by gaoxuan-haxibiao** [comment]
![2018-07-11 4 13 19](https://user-images.githubusercontent.com/36940267/42558984-5cbe713e-8525-11e8-81de-0ebcbae6a3d2.png)

初步排版  

需要最新热门的视频排序
