### ISSUE TITLE
有剑气网站问题汇总

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/ainicheng#151]
1.消息提示无法消除
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/72dea954-2f90-4aed-8e2d-b9329af1aa94)
2.首页专题点击无法进入专题
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/e8a426ea-eb57-4cdb-baba-af5117511f47)
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/8e00c02d-42df-45d7-b54e-280524bd41bc)
3.右侧推荐作者，点击换一批反应延迟，点击关注无反应
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/6fb617dc-90ba-4eaf-8ba3-566f60d014f1)
4.文章上首页限制，有些文章可以上首页，有些不行，是跟选取的图片的大小长宽比例有关吗？
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/e558ec7a-bb11-49cc-b0ad-94a865db7777)
5.视频wu'fa'shang'chuan无法上传
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/6b4f91cf-6634-413a-b894-d3a59709b059)

目前先报这些比较明显的，后续有问题会再更新；

**Comment by ayaotz233** [comment]
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/f7a22d54-f933-480c-947f-fe04a753c50c)
文章底部专题添加这个地方，点过之后，里面的专题与实际的专题不符，少了很多新建的；无法直接选取，但是可以搜索到；
搜索也是只有回车交互，点击放大镜是没有反应的；
搜索的关键字算法有问题？只能搜出开头与关键字一致的专题，如“动漫壁纸”专题，只能搜索动漫得到，搜索壁纸是没有这个专题的；
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/e4616bec-25f9-46e4-a323-f863c3ac98e1)

**Comment by caizhigang1997** [comment]
最后的投稿搜专题已经修复,  推荐作者点关注没反应也修复了, 其它问题老张说没修的必要
