### ISSUE TITLE
爱你城专题创建失败

### ISSUE THREAD

**Issue by ayaotz233** [haxibiao/ainicheng#154]
填完所有信息后点击创建，页面自动跳转回专题创建页，并且专题创建不成功
![image.png](https://images.zenhubusercontent.com/5aa9f86e4b5806bc2bcaec2d/1a60b5fe-d0b7-44ba-b0dd-e2f29f97a50d)

**Comment by caizhigang1997** [comment]
后台逻辑没问题，问题是后端未对输入参数做校验处理.已经纳入后端工作计划。

**Comment by ayaotz233** [comment]
注意输入内容长度存在限制，已经确认过。
