### ISSUE TITLE
王者英雄介绍专题下的爬虫文章，在专题栏页面显示有主配图，但是打开文章，没有图片

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#155]
王者英雄介绍专题下的爬虫文章，在专题栏页面显示有主配图，但是打开文章，没有图片
![1](https://user-images.githubusercontent.com/36875687/42919315-df5927e6-8b43-11e8-93f7-63bf10fcf79f.png)
![2](https://user-images.githubusercontent.com/36875687/42919434-672fd3fe-8b44-11e8-9368-d0f8a90994bb.png)

**Comment by lilianwoo** [comment]
专题LOL英雄介绍专题也是一样，题栏页面显示有主配图，文章没有图片

**Comment by caizhigang1997** [comment]
该文章在抓取的时候文章体中就没有保存图片.后端不好修复这个问题.如果觉得这部分内容价值不大可以考虑下架.
