### ISSUE TITLE
爱你城专题管理搜索栏点击后跳转数据错误

### ISSUE THREAD

**Issue by yangliu9494** [haxibiao/ainicheng#158]
如图
![asd](https://user-images.githubusercontent.com/40386628/43057288-eef0e9ea-8e73-11e8-85d4-5d5a651f9d47.jpg)

点击后

![qwe](https://user-images.githubusercontent.com/40386628/43057287-ecb89394-8e73-11e8-9403-c0f2fde21ed0.png)

**Comment by XiaoXinMing** [comment]
已经修复
2018年07月23日16:42:04
![2018-07-23 16-41-53](https://user-images.githubusercontent.com/39290488/43066477-5753ec1c-8e97-11e8-9266-38417359b103.png)

**Comment by yangliu9494** [comment]
搜索栏下面的排序可以整理下，如图，我查找王者荣耀，在前面6页没有找到王者荣耀这4个字的指定专题，只是相关专题，6页以后全是不相关的专题，但是我要找的是指定专题，是否可以修改排序为首个是搜索内容指定专题，下面再是相关专题？

![asd](https://user-images.githubusercontent.com/40386628/43110614-9030ee44-8f1f-11e8-9152-89f8bb66d583.jpg)

**Comment by XiaoXinMing** [comment]
已经完成：
2018年07月24日15:18:13
从上而下是精准查询结果->模糊查询结果

![2018-07-24 15-17-29](https://user-images.githubusercontent.com/39290488/43122818-e1d26a7c-8f54-11e8-8e54-0b87f03b0bf0.png)

**Comment by yangliu9494** [comment]
已完成
