### ISSUE TITLE
首页点击更多专题页面很卡，全部专题页翻页也会很卡

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#161]
首页点击更多专题页面很卡，全部专题页翻页也会很卡
![1](https://user-images.githubusercontent.com/36875687/43062336-0f735eac-8e8b-11e8-9613-be869ca87552.png)

**Comment by ivanzhang2** [comment]
精简返回的专题数从24减少到12后，稍微提升了速度
