### ISSUE TITLE
同一篇投稿文章，琼琼账号显示可以接收投稿或者拒绝，我这边显示投稿文章已经被撤回，并且我点击文章也没办法消除消息提示

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#165]
同一篇投稿文章，琼琼账号显示可以接收投稿或者拒绝，我这边显示投稿文章已经被撤回，并且我点击文章也没办法消除消息提示
![1](https://user-images.githubusercontent.com/36875687/43111860-ba7a6a62-8f25-11e8-8ab6-4c841467682c.jpg)
![2](https://user-images.githubusercontent.com/36875687/43111867-c21f3c16-8f25-11e8-92f4-bc068d3b37b5.png)

**Comment by caizhigang1997** [comment]
已经修复
