### ISSUE TITLE
评论消息入口 以及 个人动态页   点击视频标题无法进入对应的视频详情页

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#166]
![qq20180724-120109](https://user-images.githubusercontent.com/36940267/43119730-27ee5bfc-8f4a-11e8-9a3d-3cbd7bdc5827.png)
![qq20180724-135612](https://user-images.githubusercontent.com/36940267/43119737-346a4d82-8f4a-11e8-82d5-42bb99781129.png)

**Comment by caizhigang1997** [comment]
@gaoxuan-haxibiao 已经解决
