### ISSUE TITLE
个人主页的动态页  无法显示评论等最近动态

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#167]
动态显示不全 

![qq20180724-120229](https://user-images.githubusercontent.com/36940267/43119883-c7c0ac34-8f4a-11e8-9686-97f13cd887e9.png)

**Comment by caizhigang1997** [comment]
原因是默认只显示最近的10条动态，这个地方会考虑用异步方式加载实现 @gaoxuan-haxibiao

**Comment by XiaoXinMing** [comment]
部分评论老数据有问题， @"用户" 没有A标签
@caizhigang1997

**Comment by XiaoXinMing** [comment]
已经修复完成：
2018年07月26日17:04:33
