### ISSUE TITLE
视频播放页面，在左边增加一个喜欢的人数，把喜欢的按钮移动到右边

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#168]
视频播放页面，在左边增加一个喜欢的人数，把喜欢的按钮移动到右边
![2](https://user-images.githubusercontent.com/36875687/43131856-a5229706-8f6c-11e8-9c06-58395ff226e4.png)

**Comment by caizhigang1997** [comment]
老王移动一下按钮就OK。不显示人数，问题已经找到，是后端的原因。

**Comment by caizhigang1997** [comment]
后端工作已经完成
