### ISSUE TITLE
上传的视频被喜欢，收不到消息提示

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#169]
上传的视频被喜欢，收不到消息提示
![1](https://user-images.githubusercontent.com/36875687/43132055-3961d4cc-8f6d-11e8-874a-4da44fc2f192.png)
![2](https://user-images.githubusercontent.com/36875687/43132061-3f4b0c78-8f6d-11e8-9db8-75a5587f23e3.png)

**Comment by caizhigang1997** [comment]
问题已经找到，但是另外发现。网站的评论点赞功能未实现消息通知。等一起做完给你回复

**Comment by caizhigang1997** [comment]
已经修复
