### ISSUE TITLE
爱你城网站 手机端未登录看不到专题

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#18]
切换一下状态  让登录未登录都可以看到热门专题 
这个热门专题 先显示 表情包 昵称 头像  游戏 四个专题分类 （可以五个的话 再加上爱你城官方小课堂 如果点击换一批按钮的 再随机换一批）

**Comment by tanyanqiong** [comment]
![微信图片_20180403142842.jpg](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/9dbe38ea-38f1-4f6a-9942-d4ab53148c67)
zhunt
专题的显示还是不是我要的那四个哦

**Comment by pengconguses1** [comment]
已修复
