### ISSUE TITLE
爱你城网站新功能

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#19]
1.首页的热门专题 一进来固定的七个是
游戏 昵称 头像 句子 表情包 情感树洞 情侣日常 爱你城官方小课堂 
2.首页加一个置顶功能 可以置顶三篇文章 一直显示在首页前三的位置
3.让除掉爬虫自动更新的文章自动排序到 真实用户发布的之后 这个排序是 真实用户文章>爬虫文章 
这两个是独立不交融的，里面在按时间最新顺序排列。
4.被点赞、喜欢、评论过的文章，就当刷新发布时间了，按当时动作发生的时间排序，往前跳。

**Comment by pengconguses1** [comment]
建议首页可以三种排序方式 默认按照最新评论  

还可以按照点赞最多 以及喜欢最多

**Comment by pengconguses1** [comment]
基本都已经完成
