### ISSUE TITLE
新抓取网站

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#20]
http://www.touxiang.cn
头像网：
抓：女生头像 男生头像 情侣头像 个性头像

https://www.duitang.com
堆糖网：
抓：摄影、文字句子、头像、古风、壁纸、摄影、Q版头像定制。

**Comment by pengconguses1** [comment]
堆糖已经抓取完毕了 基本都是图片合成的文章

**Comment by ivanzhang2** [comment]
这个是爬虫工作，暂时freeze, 我们最近专注手动制作原创内容和视频...

**Comment by XiaoXinMing** [comment]
暂时关闭： ivan
