### ISSUE TITLE
爬虫自动更新的有些文章没有主要图 

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#21]
文章里本身有图片，但是出现在首页时没有主要图。

**Comment by pengconguses1** [comment]
这个问题已经修复

**Comment by tanyanqiong** [comment]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/924b3b39-21fd-488b-9238-0b05c181a095)
这个问题依然存在 需要提出主要图

**Comment by tanyanqiong** [comment]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/41eaf560-1aca-434d-a04a-0fc077d4bc39)

**Comment by tanyanqiong** [comment]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/adb7c006-3aa8-4500-8280-24ddc583eb37)

**Comment by caizhigang1997** [comment]
这个问题是因为数据库中的数据存的不规范。可能是早期的爬虫脚本没有实现统一的爬虫接口。主要的分类有: <b>唯美图片 唯美摄影 可爱图片<b>。打算修复数据。

**Comment by XiaoXinMing** [comment]
这个和网站主功能和主内容关系不大，暂时关闭
