### ISSUE TITLE
搜索功能有问题

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#25]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/f7428604-4463-4d37-a37b-614a183b8869)
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/03b0bdf7-5a3f-4c77-baac-ea1556417068)
有好几篇奕星的文章 只搜出了一张 标题里有奕星的反而搜不出来
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/3f50dc5f-f673-4b3e-ac4a-6d1485bb280f)
问答里的搜索功能也是 有与奕星相关的文章和图片而点不动搜索（搜遍网站没有才会点不动）
点动搜索的话 也会缺少部分内容相关的图片

**Comment by pengconguses1** [comment]
已经修复  搜索排序中加入只搜标题和只搜文章内容
