### ISSUE TITLE
个人主页里的粉丝 还是点不动 只能点动关注和文章

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#26]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/07e0aade-5699-4e3d-ac32-90b13008abdc)

**Comment by tanyanqiong** [comment]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/7dce849e-1f3f-47f8-91e9-809e36cd0d4c)

个人主页里的关注和粉丝数据 都只能看到三个 需要修复。

**Comment by caizhigang1997** [comment]
这个issue已经解决，但是测试的时候在这个地方又新发现了一个问题：没有加载更多的功能，当数据超过10条时，部分数据显示不出来。后面我打算参考<b>分类下文章的异步加载方式</b>实现相同的功能。

**Comment by ivanzhang2** [comment]
肖新明来实现下这个需求
