### ISSUE TITLE
弄一下文章标题下面那个喜欢的按钮

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#27]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/b61a332b-5b2f-441e-8ca4-e9ea330880e8)
浏览和评论的图标都能直接点动 喜欢不行

**Comment by tanyanqiong** [comment]
顺便把评论的那个按钮弄一下 点到评论 就不看文章了直接跳文章

**Comment by zoumin-hxb** [comment]
喜欢就是只读的

**Comment by zoumin-hxb** [comment]
a链接锚点这里有php代码，  彭聪看一下吧。
