### ISSUE TITLE
免费素材库做的很棒 但还有一点点要改进的

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#29]
选择图片以后 图片到了文章中的那一句添加说明..什么的就不要了
而且这个图片可以显示在底下 已选配图里 直接用作主要图

**Comment by pengconguses1** [comment]
这个邹敏去弄一下~ 貌似都在js里

**Comment by pengconguses1** [comment]
这个地方我不是很明白js的机制,

这部分代码是张总写的 很复杂.

如果邹敏有空的话 可以一起讨论一下

**Comment by ivanzhang2** [comment]
这个issue，@谭艳琼， 可以的话，再看看，是否还存在，还存在的话，用个截图吧
