### ISSUE TITLE
注册之后的默认头像没有吗.....

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#30]
![image](https://user-images.githubusercontent.com/36940267/38967611-6a29c8f2-43ba-11e8-9255-fb80b8ec1b85.png)

**Comment by pengconguses1** [comment]
已经修复

**Comment by tanyanqiong** [comment]
之前默认头像要用的那组图片我已经打成一个压缩包发送了，现在依然还是原来的女头像。

**Comment by wangyukun-hxb** [comment]
这个默认头像需要 @caizhigang1997 你的帮助😁

**Comment by caizhigang1997** [comment]
线上已经解决

**Comment by tanyanqiong** [comment]
测试了，已ok！
