### ISSUE TITLE
专题投稿里的链接不对

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#31]
![image](https://user-images.githubusercontent.com/36940267/38967686-d2550be4-43ba-11e8-9fad-22f850625fd1.png)

点击写篇新文章没有跳到新版编辑器
![image](https://user-images.githubusercontent.com/36940267/38967658-b349cf6e-43ba-11e8-9e65-9915048d2ef6.png)

**Comment by zoumin-hxb** [comment]
投稿里面的新建专题链接提示-->权限不足问题。

**Comment by zoumin-hxb** [comment]
普通用户不能创建专题？？？？   
那是否可以只有编辑身份才出现这个新建专题，不然会有种错觉感。

**Comment by pengconguses1** [comment]
是的  编辑用户才出现这个 稍后我去改一改vue
