### ISSUE TITLE
其他消息里来消息没有内容显示出来

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#33]
![2018-04-19 10-34-43屏幕截图.png](https://images.zenhubusercontent.com/5ab4524a4b5806bc2bcc0bd5/1fa6cc50-35b4-445f-a242-5360d511c1db)
其他消息里来消息没有内容显示出来

**Comment by pengconguses1** [comment]
本来就没有消息 通知系统的bug

**Comment by zoumin-hxb** [comment]
其他消息里面是会有消息的，比如： 你投稿的文章是否被收录的消息........
