### ISSUE TITLE
投稿和文章里 加一个 选择上首页的按钮 用户编辑器加上可以让用户自己选择主要图

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#35]

**Comment by ivanzhang2** [comment]
1. 投稿和文章里 加一个 选择上首页的按钮? 
 这个不太明白

2. 用户编辑器加上可以让用户自己选择主要图
这个功能没必要做，自动提取某张图就行，不好我们就换算法，如果实在还不行，超级编辑账户和管理员可以编辑文章，那时候可以再手动换个配图。一般情况下不需要，除非某篇很重要的用户文章上了首页，需要手动干预一下
