### ISSUE TITLE
动态没有正文，专题没有取头像

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#36]
![2018-04-24 09-44-14屏幕截图.png](https://images.zenhubusercontent.com/5ab4524a4b5806bc2bcc0bd5/4e22c61d-0968-474c-9f2a-6104cfc15cd3)

**Comment by pengconguses1** [comment]
哪个位置没有取头像?

**Comment by pengconguses1** [comment]
这个问题已经修复了 是视图中的渲染条件有错误

**Comment by tanyanqiong** [comment]
已修复
