### ISSUE TITLE
爱你城 dota英雄资料样式

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#37]
背景原因： 上周我让爬虫更新了dota2的道具资料，由于网站从外链平台引入了一些流量，得到了一页dota2道具的关键词，移动权重终于到1了。

解决方案： 需要邹敏在 haxibiao.com 相应的fix/ *.css 下修复样式， 然后彭聪把样式用到相应的项目下的相应的专题下.

好处: 趁热打铁的铺上dota2英雄资料，能顺势做高pc权重，把pc客户端的权重也做到1。

要求：仿照dota2官网的英雄资料，写一个使哈希表库里的dota2英雄资料文章数据排列简单明了，框架清晰。

**Comment by ivanzhang2** [comment]
dota 英雄资料文章库位置：
https://haxibiao.com/article?category_id=367

需要邹敏在  haxibiao.com 相应的fix/ *.css 下修复样式， 然后彭聪把样式用到相应的项目下的相应的专题下....

**Comment by zoumin-hxb** [comment]
爬资料下来的原始网站是哪一个，我去看看。

**Comment by tanyanqiong** [comment]
http://www.dota2.com.cn/heroes/index.htm

**Comment by zoumin-hxb** [comment]
可以了

**Comment by pengconguses1** [comment]
已经整合到本地的爱你城  准备测试

**Comment by pengconguses1** [comment]
在爱你城的效果有点不一样 可能还需要小修一下

**Comment by pengconguses1** [comment]
已经确认合理 发布到生产环境

**Comment by zoumin-hxb** [comment]
从哈希表爬过来的资料多了好多  <br/> 标签？  布局都被撑破了好多。

**Comment by zoumin-hxb** [comment]
《br /》标签

**Comment by pengconguses1** [comment]
不知道 你看看 我直接把你哈希表的scss打包拿过来的 两个站样式不一样 你看看是不是起了冲突

**Comment by zoumin-hxb** [comment]
样式没有冲突，是多了很多的《br/》换行标签

**Comment by pengconguses1** [comment]
换行怎么会把样式撑破的 

我从哈希表爬过来的 应该数据都是一样的.

**Comment by zoumin-hxb** [comment]
数据是一样的，但是html结构不一样了，不知道为什么多了很多哈希表上没有的br 换行标签

**Comment by pengconguses1** [comment]
你可以试着修复一下 琼琼认为这样还行. 

我觉得还好  看起来还不错

**Comment by zoumin-hxb** [comment]
已经可以了

**Comment by tanyanqiong** [comment]
现在看着还不错了 应该算可以了。
