### ISSUE TITLE
我真的非常需要一个投稿可以上首页的按钮 

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#38]
我已经提了好多遍了 置顶和取消真的很麻烦 上了首页 按时间排序可以刷新刷下来吧

**Comment by pengconguses1** [comment]
投稿到的专题如果是允许不审核 默认就会直接上首页～  但是不会在置顶的文章之前这个是刚开始就确定好的了.

我在个人编辑页面加一个添加置顶文章的按钮.

**Comment by pengconguses1** [comment]
我在个人编辑页面给你添加了一个置顶首页的接口

如图 ![2018-04-27 13-40-16屏幕截图.png](https://images.zenhubusercontent.com/5ab1c31f4b5806bc2bcbb5b6/4024bfd1-00cc-4506-b5c8-9fab77819350)

推送参数:
如果你选择了熊账号和百度推送 给外部接口提交文章的话.那这个参数你应该填写需要推送的文章数量

如果你选择置顶文章或者撤销置顶文章的话 这个参数你应该填写置顶文章的ID

推送类型:
按需要选择 千万不要选错.弄错了会造成意想不到的操作.

好在这几个接口都不会修改数据库.
