### ISSUE TITLE
文章在缩略界面，点开阅读的icon是可以跳进去阅读的，同理，点到评论的icon直接跳到评论框，点到喜欢的icon直接标记上喜欢。

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#45]
❤️去掉hover， comment icon, go to comments section .

**Comment by ivanzhang2** [comment]
评论 - 去评论 seciton,
喜欢 - 去掉hover

**Comment by ivanzhang2** [comment]
最后一个点到喜欢的ｉｃｏｎ，取消鼠标手势就行了，　直接算喜欢操作就不做了，简书都不在这做交互。

**Comment by tanyanqiong** [comment]
@wangyukun-hxb 
评论到位了 喜欢的交互还没有去掉

**Comment by wangyukun-hxb** [comment]
@tanyanqiong 
阔以了
