### ISSUE TITLE
创作编辑器，统一重新看一遍的问题

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#48]
1.普通用户写文章，保存之后退出，再点开除了标题之外，所有的内容全丢失了。
2.普通用户发布文章之后，不能显示的主要图。

**Comment by ivanzhang2** [comment]
1. 自动保存 - ivan
2. 显示主配图： 更新代码后，已修复 -  谭艳琼测试

**Comment by tanyanqiong** [comment]
1.内容依然丢失，甚至保存草稿，创作编辑器里不会缓存内容，而网站上保存的内容会覆盖之前发表的文章。
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/4cdc2eb9-5ce4-4c52-a66d-7f274ed2ef1c)
2.普通用户可以自己选主要配图了。

**Comment by ivanzhang2** [comment]
谭艳琼，
验证下这里的问题，然后看是否可以关了

创作编辑器不需要用户自己选主配图，自动选择其中一张图做列表的配图的

**Comment by XiaoXinMing** [comment]
这个已经修复了
