### ISSUE TITLE
爱你城抓取任务-句子迷

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/ainicheng#5]
域名：http://www.juzimi.com/
权重：百度权重：7
需要抓取的分类：小说摘抄、电影台词、散文美句、动漫语录、连续剧台词
（抓取的每篇字数 不能少于500字）

**Comment by pengconguses1** [comment]
爬虫已经完成 但是这个网站把我的ip封了

**Comment by pengconguses1** [comment]
已经完成  还在做迁移

**Comment by pengconguses1** [comment]
爬虫完成了 但是句子迷这个网站会封IP 我没测出来他封IP的算法  不过可以在一个时刻运行爬虫爬取需要的数据就行.

![2018-03-19 15-02-13](https://user-images.githubusercontent.com/36942035/37582251-13276d34-2b87-11e8-9819-d3aa4436c28a.png)

**Comment by pengconguses1** [comment]
发现了一个新问题 我再调试调试
