### ISSUE TITLE
全站管理员的主编辑身份也不能编辑用户的文章/选主要配图了，发布不跳转，更新时间在动。

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#55]
dongmeiwei: 管理身份，编辑文章，增加收录专题后，只显示最后一个在文章详细页

**Comment by ivanzhang2** [comment]
已修复：
dongmeiwei: 管理身份，编辑文章，增加收录专题后，只显示最后一个在文章详细页
上面的， tyq 测试

**Comment by tanyanqiong** [comment]
已修复 可以更改和编辑了
