### ISSUE TITLE
给普通用户编辑器里也加上免费素材库。

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#56]
dongmeiwei: 把外链图片 替换成 原来老编辑器 多媒体选择里的图片选择vue...

**Comment by ivanzhang2** [comment]
邹敏之前做了 编辑身份编辑器里的这个功能， 叫 ImageListModal.vue ... , 现在 编辑编辑器里恢复这个功能，然后看着给创作编辑器加上

**Comment by ivanzhang2** [comment]
雷坤，乐乐，更新下这个issue , 我记得雷坤周报里已经完成开发工作。
测试结果更新下

**Comment by leikun222** [comment]
给普通用户编辑器里也加上免费素材库,这个功能已经实现了,是要当文本框获得焦点的时候才能唤起免费素材库的modal.
