### ISSUE TITLE
这个免费素材库，不是显示最近的图片，而是搜索全网站显示相关全部（按时间倒序），或者显示最近的前十二张，同一个关键词重新搜索再换十二张显示。

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#57]
-dongmeiwei: 能搜索图片(来自哈希表全图库), 首屏显示关键词匹配的图（匹配高），然后是标题匹配，最后是相关网页匹配，超过12张后，滚动加载更多..

**Comment by ivanzhang2** [comment]
Ivan：backlog: 能搜索图片(来自哈希表全图库), 首屏显示关键词匹配的图（匹配高），然后是标题匹配，最后是相关网页匹配，超过12张后，滚动加载更多..

tyq: 测试新代码

**Comment by tanyanqiong** [comment]
普通用户可以使用问答免费素材库了
