### ISSUE TITLE
搜索功能的综合排序，根据关键词先检索大的分类，然后按浏览量高低排列显示。

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#58]
-dongmeiwei: 相关性顺序： keyowords/tags match > title contains > body contains

**Comment by ivanzhang2** [comment]
tyq：测试带　关键词　的文章，　在新代码上。。。

**Comment by ivanzhang2** [comment]
代码已同步，爱你城不再单独有这个问题
