### ISSUE TITLE
爱你城 同步代码之后需要保留的之前的地方

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#59]
![image](https://user-images.githubusercontent.com/36940246/40101810-2393d682-591b-11e8-8216-f937366c6145.png)
![image](https://user-images.githubusercontent.com/36940246/40101972-b65addd0-591b-11e8-9f8a-51b490eda708.png)

我觉得横着的图标放在导航栏更好看 之前创作按钮颜色更搭配 把同步懂美味代码黄色的地方都换回去吧

**Comment by ivanzhang2** [comment]
马上更新代码，　谭艳琼测试

**Comment by tanyanqiong** [comment]
已修复
