### ISSUE TITLE
为爱你城抓取一些后面自动更新需要的内容

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/ainicheng#6]
1.网站名称：唯美图片
域名：http://www.wmpic.me/
权重：百度权重：4
需要抓取的分类/频道：唯美图片、小清新图片、意境图片、可爱图片、唯美摄影。

需要抓取的文章内部内容片段：文章标题中含“情侣头像”“情侣壁纸”“动漫头像”“卡通头像”“小清新头像”“壁纸”“背景”字的文章。
（抓取内容的时间点最早不超过2017年1月1月）

2.网站名称：QQ名字
域名：www.oicq88.com
权重：百度权重：5
需要抓取的分类：QQ情侣名字、QQ战队名字、QQ烟字网名、QQ闺蜜网名、QQ酒字网名、QQ霸道网名、QQ小清新网名、QQ古风网名、QQ简单网名、QQ诗意网名、QQ帅气网名、QQ意境网名、QQ成熟网名、QQ伤感网名、QQ游戏网名、QQ英文网名、QQ姐妹网名、QQ符号网名， 、QQ兄妹网名。
（抓取内容的时间点最早不超过2017年1月1月）

3.网站名称：句子迷
域名：http://www.juzimi.com/
权重：百度权重：7
需要抓取的分类：小说摘抄、电影台词、散文美句、动漫语录、连续剧台词
（抓取的每篇字数 不能少于500字）

4.网站名称：4399手机游戏网
域名：news.4399.com
权重：百度权重：7
需要抓取的分类：荒野行动、旅行青蛙、王者荣耀、终结者2

**Comment by pengconguses1** [comment]
已经全部完成  第4个任务经过和pm的讨论 决定取消
