### ISSUE TITLE
热门专题依然固定成这六个

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#60]
![image](https://user-images.githubusercontent.com/36940246/40102032-f1773436-591b-11e8-88bf-03e1ce514f2b.png)
这是我之前固定好的网站六个大方向

**Comment by ivanzhang2** [comment]
新需求之一：
置顶
    -  轮播图
　－　首页文章
　－　专题置顶

**Comment by pengconguses1** [comment]
轮播图和首页文章置顶已经搞定.

现在开始为首页专题置顶

**Comment by pengconguses1** [comment]
置顶专题已经提供.
请手动置顶
