### ISSUE TITLE
爱你城首页的问题汇总

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#61]
![image](https://user-images.githubusercontent.com/36940246/40102674-b4fa4000-591d-11e8-826d-7bb2f1391774.png)

1.下载手机app旁边的图片二维码贴错了
2.作者旁边的那个签约作者的图标裂了
3.首页文章应该按时间倒序显示
4.新上榜换成7日热门，7日热门换成30日热门，30日热门换成经典热门
5.最重要的一点！！懂美味黄色的地方 都换回我们爱你城的红色 比如说 首页文章底下的小分类的标签啊 这种细节地方，还有选中时候的颜色切换，也从变黄变红，新用户注册时和登录时的选中按钮也从变黄到变红，总而言之，一切用黄色代码的地方都切换成原来的红色。

基准如下图所示
![image](https://user-images.githubusercontent.com/36940246/40102840-23070e84-591e-11e8-97a4-aaeb70bb7c90.png)

新用户登录界面的爱你城图标也崩了 需要修一下

**Comment by ivanzhang2** [comment]
雷坤看着图修，彭聪也可以

**Comment by pengconguses1** [comment]
首页文章时间倒序显示已经修复,

首页的爬虫文章全部消失了.

已经修复了大部分图裂的错误..

剩下的需要前端手动修复  老雷看一下

**Comment by pengconguses1** [comment]
@leikun222 

把爱你城的首页左上角的那三个字的样式修复一下~

**Comment by ivanzhang2** [comment]
基本修复了，关掉了，有问题后面报新的issue
