### ISSUE TITLE
爱你城用户个人主页出现的问题

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#63]
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/74b16f62-b94e-4a01-b221-6fcb583afb96)
1.大多数页面的是好的 我看的晴晴的个人主页动态是假数据
2.爱你城签约作者那里图裂了，还多了一个，去掉一个。
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/aab72d46-c701-45ae-9bd8-4bc121cacf81)
3.按评论时间倒序排列的算法有问题 我有评论的文章 并没有显示在前列

**Comment by ivanzhang2** [comment]
文章下的数字静态　已修复，　签约作者的图.... 图的问题统一修，
评论排序，已修复～
