### ISSUE TITLE
创作编辑器和投稿测试之后出现的问题

### ISSUE THREAD

**Issue by tanyanqiong** [haxibiao/ainicheng#64]
在创作编辑器里保存文章 内容会丢失 但是会覆盖掉已发布的文章 
![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/489f5003-dee7-4d76-9aa4-ee00ca1749a1)

![image.png](https://images.zenhubusercontent.com/5aab1f964b5806bc2bcb1324/b5058e24-4b10-43f0-8d51-b4ff16fa0309)

即使是编辑拒绝了的文章 依然会出现在这个专题里打上这个分类

**Comment by ivanzhang2** [comment]
修复了
