### ISSUE TITLE
视频模块的一点还存在的一些小bug

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#67]
background: 
1. 为了网站有一个流畅的视频添加体验，方便在目前app还不能上传视频的情况下，公司运营人员可以为网站上传一些剪辑的原创视频。

issues:
1. 视频上传出现的问题，PM这要给点具体的问题信息.....
2. 以及李雪晴提出关于上传视频最后一张图片截取失败, 

solution:
1. need more input.
2. 有可能是否是视频时长问题

**Comment by caizhigang1997** [comment]
关于视频截图最后一张失败的问题。原因是我们网站使用的截图工具ffmpeg默认做了加速的优化处理。后面更新视频模块milestone时,会统一做修改。到时候会邮件通知大家。

**Comment by XiaoXinMing** [comment]
找到原因了，这个issue先关闭了，后面发现再处理，这个knowledge我们写到周报博客里，记录下来
