### ISSUE TITLE
爱你城网站首页轮播图重复

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#68]
这个事情我记得琼琼提出来的，现在还能看到重复的，你们一起看看是置顶的冲突了，还是数据或者代码问题。

**Comment by caizhigang1997** [comment]
1.首页轮播图重复是因为同时上首页的两篇文章具有相同图片。
2.置顶功能稍微修复了一下，做了文章排重。但是如果两篇不同的文章具有相同的图片，上首页还是会有轮播图重复的情况。目前能想到的解决方案是用图片做hash排重，但是目前上传图片的api没有存储hash值.

**Comment by tanyanqiong** [comment]
@ivanzhang2 这个问题依然存在，隔三差五出现，想要您帮助小蔡确定一下解决方案。

**Comment by ivanzhang2** [comment]
雪晴： 改成新版本后，这个issue不容易出现了
