### ISSUE TITLE
解决分类页(专题)面tab翻页乱跳问题

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#69]
issue:
现在的专题也，第2个之后的tab翻页后，都回到了第一个tab

solution:
这个问题需要后端在翻页 里，为每个tab 传入不同的猫点， 前端再根据url传入的，trigger一下tab到制定的tab。

**Comment by tanyanqiong** [comment]
@zoumin-hxb 这个我不太了解 小蔡放到了done里 敏敏你测试一下 可以了就关掉。

**Comment by ivanzhang2** [comment]
现在点新收录，热门等tab 都固定跑到视频tab ....

**Comment by ivanzhang2** [comment]
这个看起来已经修复了，下次谁修复了，记得关一下
