### ISSUE TITLE
调整文集的数据库关系，并完整文集目录功能。并修复文集中文章数与文章数量不匹配等问题

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#71]
这个问题的背景原因，蔡志刚和肖新明说一下，后面让肖新明来修复，最后我们一起code review ...

**Comment by XiaoXinMing** [comment]
对数据库文集关系 已经重新进行了维护。
删除了article_collection 中间表
对文章数量进行了修复。
2018年07月10日16:07:08
![2018-07-10 16-07-30屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/936ea995-0152-4dec-8a00-9f1286995c62)
