### ISSUE TITLE
用户个人页，关注tab上的总数 和 头像信息面板上的关注用户数量不匹配 

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#75]
演示地址：
 https://dongdianyi.com/user/186/followings

![1.jpg](https://images.zenhubusercontent.com/5ab4524a4b5806bc2bcc0bd5/34700ec8-440f-4be5-820d-b67b7c9a1f52)

**Comment by XiaoXinMing** [comment]
已经修复

把关注的总数换成了只关注用户的总数。

![2018-07-07 17-41-10屏幕截图.png](https://images.zenhubusercontent.com/5afa69594b5806bc2bd32c60/0f14cf8f-d11c-4f1c-b11b-68dfbf059a24)

**Comment by yangliu9494** [comment]
关注用户数量不对，关注数量实际还是总关注用户数量+专题数量。
如图，我关注的实际只有10个人，显示我关注的用户有14个，实际是加上了4个专题。要去掉关注专题的数量。
![~46}Z0GIOPQ8AW)A`)LZ)5O.jpg](https://images.zenhubusercontent.com/5b28cd40f4347d493ca47c54/473f6508-edae-4717-901c-33a3fb825a0c)

**Comment by XiaoXinMing** [comment]
已经修掉了,这个是只显示前10个用户，后面的用户通过异步加载出来（异步加载的功能 还在实现当中。）

**Comment by XiaoXinMing** [comment]
Mobile端已修复。

**Comment by yangliu9494** [comment]
已检查正常。
