### ISSUE TITLE
关注 - 添加关注： 点击用户名 无法跳转至用户个人主页

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#80]
关注 - 添加关注： 点击用户名 无法跳转至用户个人主页

root cause:
vue 的连接绑定错误 ： https://dongdianyi.com/'/user/'+recommend.id

![4.png](https://images.zenhubusercontent.com/5ab4524a4b5806bc2bcc0bd5/cc7b224d-b06e-447a-96dc-aa71e921b1fb)

**Comment by leikun222** [comment]
bug 已修复

**Comment by caizhigang1997** [comment]
我测试了，没问题。板子上东西有点多，我就直接关掉了
