### ISSUE TITLE
点赞信息不同步

### ISSUE THREAD

**Issue by zoumin-hxb** [haxibiao/ainicheng#82]
https://dongdianyi.com/question 
https://dongdianyi.com/question/158
![6.png](https://images.zenhubusercontent.com/5ab4524a4b5806bc2bcc0bd5/26af6e8b-1a1b-491c-8e5f-4445c2ae334a)

**Comment by XiaoXinMing** [comment]
已修复

![2018-06-24 10-45-26](https://user-images.githubusercontent.com/39290488/41815400-4d98f760-779c-11e8-8b17-8086d837798a.png)
