### ISSUE TITLE
web页面点击楼中楼用户无法正常链接到用户主页

### ISSUE THREAD

**Issue by gaoxuan-haxibiao** [haxibiao/ainicheng#93]
![issue1](https://user-images.githubusercontent.com/36940267/41575467-386da11e-73b5-11e8-965e-cf0daae6827c.png)

![issue2](https://user-images.githubusercontent.com/36940267/41575503-52f872b6-73b5-11e8-86b4-88fcfa7d6cf9.png)

**Comment by ivanzhang2** [comment]
雷坤，你正在修网站，就一起修了吧

**Comment by leikun222** [comment]
无法正常链接到用户主页的bug已修复
