### ISSUE TITLE
制作新的视频上传UI

### ISSUE THREAD

**Issue by lilianwoo** [haxibiao/ainicheng#97]
视频上传的进度希望能放大一点，或者放在页面中间
![5](https://user-images.githubusercontent.com/36875687/41645063-75258868-74a2-11e8-892c-3ed060e3faf3.png)

具体：
1. 普通用户体验 - 模态框，上传进度提示
2.截图进度提示，换个友好点的提示图片。
3.我的视频列表UI要给出新的正在截图未完成的视频的提示。

**Comment by caizhigang1997** [comment]
视频模块正在重新开发，本issue也囊括在其中

**Comment by ivanzhang2** [comment]
这个问题，具体到新的项目管理工具下讨论吧，马上用上新的视频上传UI了
